Repository Fimba-Code/blog, pull requests merged in 2020-05, with the labels that each got.

#8 Blog Post: O que é necessário para aprender a programar?
  content/blog/2020-05-12-aprender-programar/index.md
  content/blog/my-first-blog/index.md
Labels: new post

#9 Adding Open-Graph Tags
  gatsby-config.js
  src/components/seo.js
Labels: seo:improvements

#14 Selection sort
  content/blog/2020-05-12-aprender-programar/index.md
  content/blog/2020-05-15-selection-sort/index.md
  gatsby-config.js
  package.json
Labels: new post

#15 Added gatsby feed rss support
  gatsby-config.js
  package-lock.json
  package.json
  src/components/layout.js
Labels: enhancement, seo:improvements
